version: "2.1"

networks:
  test:

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8075:8075"
      - "5005:5005"
    networks:
      - test
    command: java -Dspring.profiles.active=production -jar /project/target/orgo-0.0.1-SNAPSHOT.jar